version: '3.9'

services:
  mongo:
    image: mongo
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    environment:
      - DISPIMDB_MONGO_URI=mongodb://mongo:27017
      - DISPIMDB_DATABASE_NAME=dispimdb
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8080:8080"
