version: '3.9'

services:
  mongo:
    image: mongodb
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "5000:5000"
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8080:8080"