name: test
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        mongodb-version: [4.0, 4.2, 4.4]

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install tox-gh-actions dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        run: tox
        env:
          DISPIMDB_TEST_MONGODB_URI: mongodb://localhost:27017
          DISPIMDB_TEST_MONGODB_DB: test_ddb
          DISPIMDB_CLIENT_TEST_DISPIMDB_URL: http://127.0.0.1:5012
          DISPIMDB_DATABASE_NAME: test_ddb
          DISPIMDB_MONGODB_URI: mongodb://localhost:27017
          TOX_TESTENV_PASSENV: "DISPIMDB_TEST_MONGODB_URI DISPIMDB_TEST_MONGODB_DB DISPIMDB_CLIENT_TEST_DISPIMDB_URL DISPIMDB_MONGODB_URI DISPIMDB_DATABASE_NAME"
